spring.application.name=LIC-AI-App
# Render requires apps to listen on the PORT environment variable
server.port=${PORT:8080}

# --- GROQ API SETTINGS ---
spring.ai.openai.chat.enabled=true
# Hide the API key securely inside an environment variable
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.1-8b-instant
spring.ai.model.chat=openai

# --- POSTGRESQL DATABASE SETTINGS (Render Compatible) ---
# If using Spring AI Vector Store, swap to PGVector
#spring.ai.vectorstore.pgvector.initialize-schema=true

# Database connection safely parameterized
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/springai}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true


logging.level.org.springframework.ai.chat.client=DEBUG
